### ISSUE TITLE
a question about the longest detect distance

### ISSUE THREAD

**Issue by ovenbananaaa** [pal-robotics/aruco_ros#101]
hello，i use my zed camera for detecting the aruco code ，and what is the longest distance i can detect if i have large enough aruco code

**Comment by saikishor** [comment]
Hello @ovenbananaaa,

We haven't tested this. Basically, this totally depends on the camera and how well the intrinsic parameters are calibrated. If they are well calibrated, as long as it can detect the ARuCo marker, you could get good pose estimation.

Thank you,

Best Regards,
PAL Robotics Team.
