### ISSUE TITLE
Support of aruco for ROS2 is available?

### ISSUE THREAD

**Issue by goyalvarun02** [pal-robotics/aruco_ros#106]
Hi ,

May I know if github of aruco for ROS 2 is available  Please share the path .

or if not available May I know when can expect the ros2 of aruco

Thanks

**Comment by saikishor** [comment]
Hello!

We have started migrating our robots simulation to ROS2 and you will be able to find them online soon. However, the aruco_ros package is currently not in our near future roadmap. We would be happy to review and accept any PRs on ROS2.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by YuLiHN** [comment]
Hey may I know where are you right now? Maybe I can help.

> Hello!
> 
> We have started migrating our robots simulation to ROS2 and you will be able to find them online soon. However, the aruco_ros package is currently not in our near future roadmap. We would be happy to review and accept any PRs on ROS2.
> 
> Thank you,
> 
> Best Regards, PAL Robotics Team.

**Comment by saikishor** [comment]
Hello @YuLiHN,

Thank you for showing interest in the package. We are working on it, may be in next few weeks you can expect a version of ROS2.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by saikishor** [comment]
Hello @goyalvarun02 and @YuLiHN,

We have just released the first version of ROS2 support for the aruco_ros package. You could use it by cloning and switching to the `humble-devel` branch. Let us know once you test it. 

Thank you,

Best Regards,
PAL Robotics Team.
