### ISSUE TITLE
No marker TF frame

### ISSUE THREAD

**Issue by Jiaviz** [pal-robotics/aruco_ros#111]
I launched an aruco_ros single node and the marker could be recognized. But it's wired that no marker TF frame but realsense_camera frames can be found in the tf_frame.

Hope for a solution. Thanks!

![Screenshot from 2022-12-25 20-52-48](https://user-images.githubusercontent.com/44662300/209469330-a471b82b-3a51-4225-92ca-89cb70e666f8.png)
![Screenshot from 2022-12-25 20-53-16](https://user-images.githubusercontent.com/44662300/209469332-767e8621-912c-43f7-9a8d-a2de8b09d65c.png)
![Screenshot from 2022-1
![Screenshot from 2022-12-25 21-16-12](https://user-images.githubusercontent.com/44662300/209469446-8340719a-7f85-4898-9dc5-cbd4a7cbf518.png)
2-25 20-54-24](https://user-images.githubusercontent.com/44662300/209469336-bd2864db-2fae-4bdf-b434-bd9ea52c888a.png)
![Screenshot from 2022-12-25 21-16-12](https://user-images.githubusercontent.com/44662300/209469473-ded20ee4-4fa8-48c6-ad4e-2a9cda735037.png)

**Comment by AminSeffo** [comment]
Hey @saprrow,
I am facing exactly the same problem, did you manage to solve this and can you tell me how?
Thanks in advance

**Comment by Jiaviz** [comment]
Hi, AminSeffo
I just turned to easy_aruco and it works. Remeber to remap you camera topic to easy_aruco's default camera topic, or you can just change dafault topic name in 'src/Detector.cpp'.
________________________________
发件人: AminSeffo ***@***.***>
发送时间: 2023年2月25日 15:20
收件人: pal-robotics/aruco_ros ***@***.***>
抄送: sparrow ***@***.***>; Mention ***@***.***>
主题: Re: [pal-robotics/aruco_ros] No marker TF frame (Issue #111)


Hey @saprrow<https://github.com/saprrow>,
I am facing exactly the same problem, did you manage to solve this and can you tell me how?
Thanks in advance

―

**Comment by saikishor** [comment]
Hello @saprrow and @AminSeffo,

I apologise for the delay in responding to this issue. Regarding your issues, arucos_ros only publishes the TF, where someone subscribes to the topics published by the node as specified in this part of the code: https://github.com/pal-robotics/aruco_ros/blob/noetic-devel/aruco_ros/src/simple_single.cpp#L187-L194. You can add a subscriber to one of these topics : https://github.com/pal-robotics/aruco_ros/blob/noetic-devel/aruco_ros/src/simple_single.cpp#L131-L137 to later enable the TF broadcasting. It is done this way to not to run the aruco detection all the time and thereby to reduce the load on the PC. We hope this helps to solve your issue.

Thank you,

Best Regards,
PAL Robotics Team.
