### ISSUE TITLE
Help！

### ISSUE THREAD

**Issue by Kane1440** [pal-robotics/aruco_ros#119]
[ERROR] [1693901320.302132369]: Skipped loading plugin with error: XML Document '/opt/ros/melodic/share/aruco_pose/nodelet_plugins.xml' has no Root Element. This likely means the XML is malformed or missing..

**Comment by saikishor** [comment]
Hello @Kane1440,

Seems like you have opened the issue in the wrong repository. From the above errors, the package seems to be `aruco_pose` not `aruco_ros`.  

Thank you,

Best Regards,
PAL Robotics Team.
