### ISSUE TITLE
how to change the coordinate system

### ISSUE THREAD

**Issue by Yaoxingtian** [pal-robotics/aruco_ros#124]
Hello, now the coordinate system: z is front , but i want to change x to point front, 
could you pls. tell me how to do?

thanks so much!

**Comment by saikishor** [comment]
Hello @Yaoxingtian!

The coordinate system of aruco is fixed, you would need to apply the transform at your end once you get the pose. I hope this helps. 

Thank you,

Best Regards,
PAL Robotics Team
