### ISSUE TITLE
Marker Publisher Node Not Found

### ISSUE THREAD

**Issue by sauravag** [pal-robotics/aruco_ros#13]
Hi,

Thank you for sharing this package! I tried to run the marker_publisher.launch file but I get the following error:

ERROR: cannot launch node of type [aruco_ros/marker_publisher]: can't locate node [marker_publisher] in package [aruco_ros]

I use the following command: $roslaunch marker_publisher.launch

I am able to get the single.launch file working perfectly and can see that the marker is detected. Also, the package was compiled without errors and installed in my catkin workspace.

Would you have any tips to fix this. 

Thanks!

**Comment by jordi-pages** [comment]
@sauravag The marker_publisher executable was not include in the installation rule. Please pull your master branch and give it a try now.

**Comment by sauravag** [comment]
Thanks Jordi!

I'll try it out :)

**Comment by bmagyar** [comment]
I believe this is solved. Any feedback on it?
