### ISSUE TITLE
How to attach the AR markers on specific section of robot?

### ISSUE THREAD

**Issue by weiweikong** [pal-robotics/aruco_ros#16]
Hi, just try to attach AR markers on different section of robot, such as hand, as shown in your introduction ?

![image](https://cloud.githubusercontent.com/assets/2463397/10510287/ab6bf1ce-7364-11e5-97f6-0423bf35dc9f.png)

I checked `reemc_simulation`, and did not find result. It seems that `marker26_8cm_massless` as a standard model added in Gazebo with specitic position. But the robot model is consist of different joints and planes, should I change the texture of some part to AR markers ? or added the `marker26_8cm_massless` model fixed with some sections?

Thanks.

**Comment by bmagyar** [comment]
I've done this (back in the day) by hacking the URDF of the gripper and adding a slim textured (with the marker) rectangle onto the top surface. It's basically a sticker.
