### ISSUE TITLE
using namespace std in header

### ISSUE THREAD

**Issue by rokusottervanger** [pal-robotics/aruco_ros#17]
In the aruco header files aruco/markerdetector.h and aruco/boarddetector.h there's "using namespace std;". You probably already know this, but it's there because it was in the original aruco lib, but just to be sure: This should not be there as this forces that action onto every other file including those header files (or aruco/aruco.h). If you want to do this, only do so in the source file. Here's a question and answer about it, if you need more info: http://stackoverflow.com/questions/14575799/using-namespace-std-in-a-header-file.

**Comment by bmagyar** [comment]
Nice catch! I'll refactor that bit, updating the original lib doesn't make sense while the new aruco is now being rolled out with OpenCV ;)
