### ISSUE TITLE
Kinetic support or install from source

### ISSUE THREAD

**Issue by matwilso** [pal-robotics/aruco_ros#26]
Are there any plans to adapt this for kinetic?

~~I tried cloning and building from source, but it looks like there are problems with the opencv2 to opencv3 switch.~~ 

Building from source is fine.

Thanks

**Comment by bmagyar** [comment]
Yes I have a kinetic version planned.

**Comment by bmagyar** [comment]
Why have you closed it?

**Comment by matwilso** [comment]
I thought it was kind of a moot point, since it easy to build from source.  But if there are still plans, I will reopen it.

**Comment by awesomebytes** [comment]
Any chance to have it released for kinetic?

**Comment by bmagyar** [comment]
Yep, I'm looking into it!

**Comment by awesomebytes** [comment]
For the record, I tried the `kinetic-devel` branch on a fresh Ubuntu 16.04 64b VM, did `catkin_make install` sourced that install folder, connected the image topic to a robot and it worked.

**Comment by bmagyar** [comment]
It's on the way guys!

**Comment by bmagyar** [comment]
Release was made, let us conclude this issue by closing it :)

**Comment by awesomebytes** [comment]
<3
