### ISSUE TITLE
relationship to aruco on sourceforge

### ISSUE THREAD

**Issue by kopp** [pal-robotics/aruco_ros#28]
This is more a question than an issue: What is the relationship between the code here in `aruco` and the code [on sourceforge](https://sourceforge.net/projects/aruco/) (which is/should be the "upstream" aruco, right)?

**Comment by bmagyar** [comment]
To my knowledge the most upstream one is the one in OpenCV 3. I created
this ROS package in 2012 (!) from the version of Aruco at that time. For
ROS Kinetic (where OpenCV 3 appears first) I intend to re-create this
without the explicit copy of the library but using the one in OpenCV.

**Comment by kopp** [comment]
Ok, great!  I'm looking forward to the version with opencv3 :-)
