### ISSUE TITLE
Pose of the marker

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [pal-robotics/aruco_ros#45]
Hello ,

I am New to ROS and recently just build this package inside my workspace.

I follow the tutotial (http://sauravag.com/2015/03/how-to-tracking-aruco-marker-using-a-usb-webcam-and-ro/) but I didn't create the usb_cam-stream.launch (because I don't know put this file at where)

but I am unable to get the pose of the marker. Which topic should I echo? 

![screenshot from 2018-02-21 23-50-05](https://user-images.githubusercontent.com/35726770/36490176-9de691f4-1762-11e8-8a4c-e0f9c7a63e03.png)

**Comment by tutorgaming** [comment]
1. the launch file can be placed anywhere and can be run using "roslaunch filename.launch" 
2. Can you show the result of "rostopic list" 

3. if you read the code you will find out that [the line 143](https://github.com/pal-robotics/aruco_ros/blob/541141679911a509d333896eb4594acbfda85129/aruco_ros/src/simple_single.cpp#L143)  indicates that it will publish the result in TF format 

you can try visualizing in Rviz to see the result 

PS. I haven't tried the aruco node yet, just guess the solution

**Comment by bmagyar** [comment]
Please use [ROS answers](https://answers.ros.org/questions/) for questions.
