### ISSUE TITLE
Linking in weird/ancient platforms, error with libutil.so

### ISSUE THREAD

**Issue by awesomebytes** [pal-robotics/aruco_ros#46]
Hello. I don't expect anyone else to actually run into this problem...

But if anyone finds himself/herself encountering this error while compiling aruco_ros:

```bash
/home/vm/bin/ld: /home/vm/lib/libpython2.7.a(posixmodule.o): undefined reference to symbol 'forkpty@@GLIBC_2.0'
/lib/libutil.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I managed to get over it by adding to the catkin_make / catkin_make_isolated the flag `-DCMAKE_EXE_LINKER_FLAGS=-lutil`

I hope google indexes the issue, feel free to close it, but at least this little piece of info is somewhere to be found.

**Comment by saikishor** [comment]
Hello @awesomebytes,

Thank you for the fix. We will be closing this issue.

Thank you,
