### ISSUE TITLE
cv_bridge exception

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [pal-robotics/aruco_ros#50]
Hi,

After I run "rostopic echo /aruco_single/pose, then the error "cv_bridge exception: Unrecognized image encoding" keep looping inside the terminal and no data out from the topic /aruco_single/pose.

May I know how to solve this problem?

Regards,
Chun Jye

**Comment by bmagyar** [comment]
The exception tells you what the problem is: your input is wrong.

The reason why the issue only shows up when you try to echo the results is because aruco works on a lazy fashion and won't even touch the incoming image unless there's someone subscribed to the results.
