### ISSUE TITLE
[aruco_tracker-26] process has died 

### ISSUE THREAD

**Issue by Tetexu** [pal-robotics/aruco_ros#60]
Hi，this is my problem, as follows：
[aruco_tracker-26] process has died [pid 30152, exit code -11, cmd /home/tete/ur3_move/devel/lib/aruco_ros/single /image:=/camera/rgb/image_raw /camera_info:=/camera/rgb/camera_info __name:=aruco_tracker __log:=/home/tete/.ros/log/c99d989a-09ad-11e9-818c-8cec4b137f82/aruco_tracker-26.log].
log file: /home/tete/.ros/log/c99d989a-09ad-11e9-818c-8cec4b137f82/aruco_tracker-26*.log

How should I solve it?
Thanks！

**Comment by awesomebytes** [comment]
Without the log, the version of the package, the version of the OS, what are you trying to do, etc... it's hard to help you.
