### ISSUE TITLE
The marker generator

### ISSUE THREAD

**Issue by TFLQW** [pal-robotics/aruco_ros#72]
Thanks for your contribution! But i still have some questions
How did you generate the ar marker and arrange the id to each marker, did you use the ros package ar_marker_alvar?

**Comment by bmagyar** [comment]
`rosrun aruco optimalmarkers`

**Comment by TFLQW** [comment]
@bmagyar how could input the parameter of the marker I want to generate like 
rosrun aruco optimalmarkers ...(parameters) what is the format of this command?

**Comment by XYudong** [comment]
same question. Could you provide an example of the parameters

**Comment by XYudong** [comment]
Hope to get an example.
BTW, `rosrun aruco optimalmarkers 4 0 340 xxx 22`
The "340" means the size of the output marker. others I don't know yet.

**Comment by Wang-png** [comment]
http://chev.me/arucogen/

**Comment by XYudong** [comment]
> http://chev.me/arucogen/

Hi,
But what generated by this seems different from `rosrun aruco optimalmarkers 4 0 340 xxx 22`, which may result in inconsistency issue in detection?
