### ISSUE TITLE
ERROR: cannot launch node of type [aruco_ros/single]: aruco_ros======What should I DO?

### ISSUE THREAD

**Issue by FrankCreen** [pal-robotics/aruco_ros#80]
~/catkin_ws/src/aruco_ros/aruco_ros/launch$ roslaunch single.launch 
... logging to /home/frank/.ros/log/4194766c-98ef-11ea-a685-e4f89c9e6c27/roslaunch-frank-Lenovo-XiaoXin-V4000-11084.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.43.39:32887/

SUMMARY
========

PARAMETERS
 * /aruco_single/camera_frame: stereo_gazebo_lef...
 * /aruco_single/corner_refinement: LINES
 * /aruco_single/image_is_rectified: True
 * /aruco_single/marker_frame: aruco_marker_frame
 * /aruco_single/marker_id: 582
 * /aruco_single/marker_size: 0.034
 * /aruco_single/reference_frame: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    aruco_single (aruco_ros/single)

auto-starting new master
process[master]: started with pid [11094]
ROS_MASTER_URI=http://192.168.43.39:11311

setting /run_id to 4194766c-98ef-11ea-a685-e4f89c9e6c27
process[rosout-1]: started with pid [11107]
started core service [/rosout]
ERROR: cannot launch node of type [aruco_ros/single]: aruco_ros
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
^C[rosout-1] killing on exit
[master] killing on exit
1shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by v-lopez** [comment]
You have not sourced your ROS workspace most likely, or you have not compiled the package.
