### ISSUE TITLE
ROS 2 compatability

### ISSUE THREAD

**Issue by yanth0nybg** [pal-robotics/aruco_ros#86]
Has anyone tried running aruco node in ROS2?
If so, what distributor did you use (Diademeta/ Elusor/ Fitzroy)?
Thank you.

**Comment by v-lopez** [comment]
There's  no compatibility with ROS2 yet, or planned in the short term.

We're totally open to review and merge a PR that adds this.

**Comment by yanth0nybg** [comment]
Thank you so much, will reach out again if I decided to PR that add ROS 2 compatibility.
