### ISSUE TITLE
rostopic echo /aruco_simple/pose not working

### ISSUE THREAD

**Issue by Abhinavgandhi09** [pal-robotics/aruco_ros#87]
Config: ROS 1, Melodic, Ubuntu 18.04

Hi,

I am trying to track 2 markers with the double.launch file. The 2 markers are detected and I can see the result using image_view node in the usb_cam pkg. However, when I echo the pose and pose2 topics they are blank.

I can echo the /tf topic and see the hand and object frames being published. Please let me know if you need additional info!

**Comment by saikishor** [comment]
Hello @Abhinavgandhi09 ,

We are extremely sorry for the late response. Could you give it a shot with the new changes in the repository and get back to us?.

Thank you, 

Best Regards,
PAL Robotics Team.

**Comment by Sun-Jing-Kang** [comment]
Hi,

I have the same problem! When I do 'rostopic echo /aruco_single/pose', it seems no message be sended:

![image](https://user-images.githubusercontent.com/84486497/178744066-406d64d4-7dbb-4a0a-9c6b-4e3c2978766b.png)

When I do 'rostopic echo /aruco_single/result', I can see the result:

![image](https://user-images.githubusercontent.com/84486497/178744282-cd249b82-4122-46c4-a469-fb4d7a27e7e1.png)

What should I do for this problem? My ros in kenitic, ubuntu16.04

Thanks!

**Comment by saikishor** [comment]
Hello @Sun-Jing-Kang and @Abhinavgandhi09 

Thank you for your interest in the `aruco_ros` library. Regarding your issue, the aruco_ros single only publishes the info of the marker and its pose only for [the matching marker ID](https://github.com/pal-robotics/aruco_ros/blob/noetic-devel/aruco_ros/src/simple_single.cpp#L214-L272). The one you see in the image are all the detected ArUcos, but if the detected ArUco marker is of not the intended one, it doesn't publish the info. 

For instance, as below you might detect 100s of ArUcos but you might be interested in a specific one. You would need to specify the marker_id while launching the launch file with the argument: `markerId:=582`

![image](https://user-images.githubusercontent.com/10082428/178771480-bc176c0e-45d0-4d3d-b75d-c45d43ae7fe5.png)

We hope this solves your issue.

Thank you,

Best Regards,
PAL Robotics Team
