### ISSUE TITLE
No version for Noetic OpenCV4

### ISSUE THREAD

**Issue by RDaneelOlivav** [pal-robotics/aruco_ros#89]
Hi,

Trying to compile for noetic OpenCV 4 but its crashing everywhere. An plan for a Noetic release? Thanks

**Comment by v-lopez** [comment]
Not immediately, we may even invest time on ROS2 before noetic (which will have also OpenCV4, but will change a lot more code), but if anyone can submit a PR for noetic we'll take a look.

**Comment by felixvd** [comment]
@4lhc Is there a reason you didn't make a PR for that branch? It compiled on Noetic for me.

**Comment by 4lhc** [comment]
@felixvd I didn't make a PR because there was an issue with the marker pose that I noticed, the cause of which I was not sure of. The marker pose was always at an offset from the real position of the marker as seen in the attached image. I didn't get time to explore it further. 

![image](https://user-images.githubusercontent.com/6171913/107670519-d481f100-6cb8-11eb-84b2-1321d3db9293.png)

**Comment by OTL** [comment]
@4lhc I've checked your code on noetic, and it seems that it works perfectly for me.
![Screenshot from 2021-05-20 15-48-40](https://user-images.githubusercontent.com/207142/118933532-476bc980-b984-11eb-880f-bf986a74d386.png)

**Comment by lucamarchionna** [comment]
Hi everyone, I was trying to use this repository on Noetic but I'm having problems when compiling this package, due to the wrong version of OpenCV. 
Snce you solved the problem, how can I fix this issue? Thanks in advance.

**Comment by OTL** [comment]
I think https://github.com/4lhc/aruco_ros just works fine.

**Comment by OTL** [comment]
I think https://github.com/4lhc/aruco_ros just works fine.

**Comment by v-lopez** [comment]
@4lhc feel free to make a PR and if the issue you mention is verified we can fix it.

Actually not a PR since we won't merge to main branch, but with your permission I'll  push your commit to a new noetic-devel branch.

**Comment by 4lhc** [comment]
@v-lopez Sure, go ahead.

**Comment by v-lopez** [comment]
Done!
