### ISSUE TITLE
Pose estimation accuracy?

### ISSUE THREAD

**Issue by kevinsanity5** [pal-robotics/aruco_ros#90]
May I ask the accuracy/tolerance of the pose estimation (translation and rotation) of the ArUco marker? Is it millimeter-level for translation or bigger? And with rotation? 

Thank you very much!

**Comment by awesomebytes** [comment]
I think that mostly depends on your camera calibration and resolution (and
the quality of the printed marker).

**Comment by v-lopez** [comment]
@awesomebytes is right. The size of the squares of the aruco also has a great influence. Moslty is resolution/marker size, higher on any increases detection range and accuracy.

**Comment by kevinsanity5** [comment]
Thanks!
