### ISSUE TITLE
jetson nx run aruco_ros single got Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by 43998213** [pal-robotics/aruco_ros#93]
aruco_ros-2.1.1

root@zjh-desktop:/home/zjh/kinect_test/src/aruco_ros-2.1.1/aruco_ros/launch# rosrun aruco_ros single
[ INFO] [1622268056.314117304]: start....................
[ INFO] [1622268056.317725920]: Threshold method: THRESH_ADAPTIVE
[ INFO] [1622268056.320156689]: Marker size min: 0.02% of image area
[ INFO] [1622268056.320324468]: Detection mode: DM_FAST
[ INFO] [1622268056.517383890]: ArUco node started with marker size of 0.050000 m and marker id to track: 25
[ INFO] [1622268056.517533781]: ArUco node will publish pose to TF with rgb_camera_link as parent and camera_marker as child.
[ WARN] [1622268056.517642455]: normalizeImageIllumination is unimplemented!
Segmentation fault (core dumped)

after     dyn_rec_server.setCallback(boost::bind(&ArucoSimple::reconf_callback, this, _1, _2));

**Comment by saikishor** [comment]
Hello @43998213,

Sorry for the late response. We recommend you to clean your workspace and recompile the package. We have also pushed some new changes upstream, so make sure you pull before compiling it.

Thank you,

Best Regards,
PAL Robotics Team.
