### ISSUE TITLE
Question about accuracy

### ISSUE THREAD

**Issue by kay01-kwon** [pal-robotics/aruco_ros#94]
Hi, I'm working on a mobile manipulator project. I'm considering putting the aruco marker on the desk and attaching camera to the mobile robot to estimate the pose of the mobile robot. By the way, how much accuracy can be achieved? The camera is D435i... Also, if the required accuracy (within 5 mm) meet the actual pose estimation accuracy, then can it be possible for the aruco ros to recognize a given pose? For example, when  the initial pose x, y, z is 0.1 m, 0.01 m, 0.3 m, move the camera around, and then relocate the camera at the initial pose, can the camera find out its initial pose correctly?

**Comment by saikishor** [comment]
Hello @kay01-kwon,

We are sorry for the late response. it should work as long as there is a detection and also the intrinsics of the camera are well calibrated.

Thank you,

Best Regards,
PAL Robotics Team.
