### ISSUE TITLE
Release for Noetic

### ISSUE THREAD

**Issue by OTL** [pal-robotics/aruco_ros#99]
It seems that `aruco_ros` is ready to release for noetic now.
We are happy if you could do it!

**Comment by saikishor** [comment]
Hello @OTL ,

Sure. The release for the noetic has been requested : https://github.com/ros/rosdistro/pull/32454.

Thank you,

Best Regards,
PAL Robotics Team

**Comment by OTL** [comment]
👍👍👍
Thanks!

**Comment by saikishor** [comment]
Here is the update: 
https://github.com/ros/rosdistro/pull/32537

**Comment by saikishor** [comment]
@OTL We will be closing this issue as the above PR had been merged to the rosdistro upstream.

Thank you,

Best Regards,
PAL Robotics Team

**Comment by OTL** [comment]
Thank you for your kind great job!
